/* Edit this file to add archive content. All current copy and imagery are placeholders. */
window.ARCHIVE = {
  looks: [{ id: "look-01", title: "Placeholder Textile Study", collection: "Unverified archive placeholder", heroImage: "images/look-01-placeholder.png", heroAlt: "Placeholder editorial study of a layered garment on a mannequin.", details: [
    { id:"knit", x:48, y:31, title:"Open-knit layer", component:"Placeholder component", materials:"To be confirmed", construction:"To be confirmed", description:"Replace this sample copy with verified garment information.", context:"Placeholder context — add the conceptual meaning once it is documented.", image:"images/look-01-placeholder.png" },
    { id:"drape", x:52, y:55, title:"Layered drape", component:"Placeholder component", materials:"To be confirmed", construction:"To be confirmed", description:"A sample interactive note for positioning and editorial hierarchy.", context:"Add verified project context here.", image:"images/look-01-placeholder.png" },
    { id:"stripe", x:54, y:72, title:"Striped textile", component:"Placeholder component", materials:"To be confirmed", construction:"To be confirmed", description:"Use this record as a template for a detail image, technique and designer note.", context:"Add verified process or collection context here.", image:"images/look-01-placeholder.png" }
  ] }],
  houseCodes: [["Infinite Godet","Placeholder explanation — add a verified house-code note."],["Magical Seams","Placeholder explanation — add a verified house-code note."],["Memory Accumulation","Placeholder explanation — add a verified house-code note."],["Unfinished Flowers","Placeholder explanation — add a verified house-code note."],["Bead Memory","Placeholder explanation — add a verified house-code note."],["French Stripe","Placeholder explanation — add a verified house-code note."],["Soft Adaptation","Placeholder explanation — add a verified house-code note."],["Garment Relocation","Placeholder explanation — add a verified house-code note."],["Pattern Ghosts","Placeholder explanation — add a verified house-code note."]],
  process: [["Sketches","Add verified sketches or working notes."],["Pattern cutting","Add imagery and notes from pattern development."],["Samples","Add sample studies, labels, or fitting records."],["Textile experiments","Add material tests and close-up documentation."],["Sewing details","Add construction observations and process imagery."],["Fittings","Add approved fitting images and notes."]]
};
